#!/usr/bin/env python3

from pathlib import Path

project_path = Path.cwd()


def ensure_ruff_config():
    """
    Ensures that the ruff config exists in ``pyproject.toml``.
    """
    pyproject_path = project_path.joinpath("pyproject.toml")
    with pyproject_path.open("r+") as f:
        if "[tool.ruff.lint]" not in f.read():
            f.writelines(
                [
                    "\n" "[tool.ruff.lint]\n",
                    'select = ["ALL"]\n',
                ]
            )


ensure_ruff_config()
# Remove example file generated by uv.
project_path.joinpath("hello.py").unlink(True)
